const Map<String, String> ar = {
  'cat': 'قط',
  'dog': 'كلب',
  'bird': 'طير',
  'cats': 'قطط',
  'dogs': 'كلاب',
  'birds': 'طيور',
  'enterYourQuestion': 'ادخل سؤالك',
  'types': 'انواع',
  'foods': 'طعام',
  'addImg': 'أضف صورة',
  'equipments': 'معدات',
  'addConsult': 'أضف استشارة',
  'photo_from': 'إختر الصورة من',
  'consulting': 'استشارة',
  'total': 'المجموع الكلي',
  'subTotal': 'المجموع الجزئي',
  'shipping': 'التوصيل',
  'tax': 'الضريبة',
  'jd': 'د.أ',
  'swipeToDEl': 'مرر لحذف المنتج',
  'itemCountinCart': 'منتجات في سلتك',
  'yourCartEmpty': 'سلة مشترياتك فارغة',
  'myCartDrawer': 'سلة مشترياتي',
  'addConsulting': 'إضافة استشارة',
   'username':'اسم المستخدم',
   'pass':'كلمة المرور',
   'confirm':'تأكيد كلمة المرور',
   'login':'تسجيل الدخول',
   'register':'التسجيل',
   'guest':'زائر',
   'lang':'اللغة',
   'enterCode':'ادخل كود التفعيل',
   'code':'كود التفعيل',
   'logoutDrawer':'تسجيل الخروج',
   'home':'الرئيسية',
   'verify':'تم',
  'emailVerify':'يرجى التحقق من بريدك الاكتروني لتأكيد البريد الاكتروني، ثم قم بتسجيل الدخول باستخدام البريد الاكتروني وكلمة المرور',
   'noComment':'لا يوجد تعليقات!',
   'comment':'التعليق',
   'addComment':'اضف تعليق',
   'addSuccess':'تمت الاضافة الى السلة',
   'checkout':'ادفع الان',
   'email':'البريد الاكتروني',
   'notMatch':'كلمتي المرور غير متطابقتين',
  'invalidEmail':'البريد الاكتروني غير صالح',
  'passShort':'كلمة المرور قصيرة جدا',
};
