const Map<String, String> en = {
  'cat':'Cat',
  'dog':'Dog',
  'bird':'Bird',
  'cats':'Cats',
  'dogs':'Dogs',
  'birds':'Birds',
  'types': 'Types',
  'foods': 'Foods',
  'enterYourQuestion': 'Enter Your Question',
  'addImg': 'add an Image',
  'equipments': 'Equipments',
  'consulting': 'Consulting',
  'addConsulting': 'Add Consulting',
  'addConsult': 'Add Consult',
  'photo_from': 'Choose photo from',
  'verify':'Verify',
  'username':'Username',
  'pass':'Password',
  'noComment':'No Comment!',
  'enterCode':'Enter Verification Code',
  'code':'Verification Code',
  'comment':'Comment',
  'addComment':'Add Comment',
  'confirm':'Confirm Password',
  'login':'Login',
  'addSuccess':'Added to Cart',
  'register':'Register',
  'email':'Email',
  'home':'Home ',
  'lang':'Language',
  'logoutDrawer':'Logout',
  'guest':'Guest',
  'myCartDrawer': 'My Cart',
  'yourCartEmpty': 'Your crt is empty',
  'itemCountinCart': 'Items in your cart',
  'total': 'Total',
  'checkout':'Pay Now',
  'swipeToDEl': 'Swipe to remove item',
  'subTotal': 'Sub Total',
  'shipping': 'Delivery',
  'tax': 'tax',
  'jd': 'JD',
  'invalidEmail':'Invalid Email',
  'passShort':'Password is too short!',
  'notMatch':'Not Match!',
};